# Google Maps Style Configuration
# This file defines the colors and styling for map export in Google Maps style

[background]
color = "#F8F7F7"  # Google Maps background color

[water]
color = "#A5BFDD"  # Google Maps water color
opacity = 1.0

[landuse]
forest = "#CBD8C3"           # Google Maps forest color
residential = "#EBE6DC"      # Google Maps residential
commercial = "#EBE6DC"       # Same as residential in Google Maps
industrial = "#d1d0cd"       # Google Maps industrial
cemetery = "#d1d0cd"         # Google Maps cemetery
retail = "#EBE6DC"

[leisure]
park = "#b5d29c"             # Google Maps park color
playground = "#b5d29c"
sport = "#d5e1dc"            # Google Maps sport
recreation_ground = "#b5d29c"
garden = "#b5d29c"

[natural]
wood = "#CBD8C3"             # Google Maps forest
forest = "#CBD8C3"
grass = "#b5d29c"
grassland = "#b5d29c"
scrub = "#CBD8C3"

[aeroway]
default = "#d1d0cd"          # Google Maps aeroway color

[buildings]
fill = "#E8E9ED"             # Google Maps building color
stroke = "#d0d0d0"
stroke_width = 0.2

[railway]
rail_color = "#a1a1a1"
rail_width = 2.0
rail_dash_color = "white"
rail_dash_width = 1.0
rail_dash_pattern = "8,4"

[boundaries]
administrative_color = "#818181"
administrative_width = 1.5
administrative_dash = "5,3"
administrative_opacity = 0.7

[labels]
# Font styling for labels
font_family = "Noto Sans"
road_label_stroke = "#ffffff"
road_label_stroke_width = 3
poi_label_stroke = "#ffffff"
poi_label_stroke_width = 2
place_label_stroke = "#ffffff"
place_label_stroke_width = 2

# Road styling with nested tables for better structure
[roads.motorway]
color = "#B9C8D6"
width = 4.0
border_color = "#A5B4C2"
border_width = 1.0

[roads.motorway_link]
color = "#B9C8D6"
width = 2.5
border_color = "#A5B4C2"
border_width = 0.5

[roads.trunk]
color = "#B9C8D6"
width = 3.5
border_color = "#A5B4C2"
border_width = 1.0

[roads.trunk_link]
color = "#B9C8D6"
width = 2.0
border_color = "#A5B4C2"
border_width = 0.5

[roads.primary]
color = "#B9C8D6"
width = 3.0
border_color = "#A5B4C2"
border_width = 1.0

[roads.primary_link]
color = "#B9C8D6"
width = 2.0
border_color = "#A5B4C2"
border_width = 0.5

[roads.secondary]
color = "#B9C8D6"
width = 2.5
border_color = "#A5B4C2"
border_width = 0.8

[roads.secondary_link]
color = "#B9C8D6"
width = 1.8
border_color = "#A5B4C2"
border_width = 0.5

[roads.tertiary]
color = "#B9C8D6"
width = 2.0
border_color = "#A5B4C2"
border_width = 0.6

[roads.unclassified]
color = "#B9C8D6"
width = 1.8
border_color = "#A5B4C2"
border_width = 1.0

[roads.residential]
color = "#B9C8D6"
width = 1.5
border_color = "#A5B4C2"
border_width = 1.0

[roads.service]
color = "#B9C8D6"
width = 1.0
border_color = "#A5B4C2"
border_width = 0.5

[roads.living_street]
color = "#B9C8D6"
width = 1.5
border_color = "#A5B4C2"
border_width = 0.8

[roads.pedestrian]
color = "#B9C8D6"
width = 1.2
border_color = "#A5B4C2"
border_width = 0.5

[roads.footway]
color = "#B9C8D6"
width = 1.0
border_color = "#A5B4C2"
border_width = 0.5

[roads.path]
color = "#B9C8D6"
width = 1.0
border_color = "#A5B4C2"
border_width = 0.5

[roads.cycleway]
color = "#B9C8D6"
width = 1.0
border_color = "#A5B4C2"
border_width = 0.5

[roads.track]
color = "#B9C8D6"
width = 1.0
border_color = "#A5B4C2"
border_width = 0.3

[roads.steps]
color = "#B9C8D6"
width = 0.8
border_color = "#A5B4C2"
border_width = 0.3

# POI styling with nested tables
[pois.restaurant]
color = "#e74c3c"
radius = 4.0

[pois.cafe]
color = "#e74c3c"
radius = 4.0

[pois.fast_food]
color = "#e74c3c"
radius = 4.0

[pois.hospital]
color = "#e5c6c3"
radius = 5.0

[pois.school]
color = "#3498db"
radius = 4.5

[pois.university]
color = "#3498db"
radius = 4.5

[pois.bank]
color = "#27ae60"
radius = 4.0

[pois.pharmacy]
color = "#8e44ad"
radius = 3.5

[pois.fuel]
color = "#f39c12"
radius = 4.0

[pois.police]
color = "#2c3e50"
radius = 4.0

[pois.fire_station]
color = "#e74c3c"
radius = 4.5

[pois.parking]
color = "#95a5a6"
radius = 3.0

# Shop POIs
[pois.shop_supermarket]
color = "#2ecc71"
radius = 4.0

[pois.shop_bakery]
color = "#f39c12"
radius = 3.5

[pois.shop_clothing]
color = "#9b59b6"
radius = 3.5

[pois.shop_convenience]
color = "#2ecc71"
radius = 3.0

# Tourism POIs
[pois.tourism_hotel]
color = "#3498db"
radius = 4.0

[pois.tourism_attraction]
color = "#e74c3c"
radius = 4.5

[pois.tourism_museum]
color = "#8e44ad"
radius = 4.0

[pois.tourism_information]
color = "#34495e"
radius = 3.0

# Leisure POIs
[pois.leisure_park]
color = "#27ae60"
radius = 5.0

[pois.leisure_playground]
color = "#f1c40f"
radius = 3.5

[pois.leisure_sports_centre]
color = "#e67e22"
radius = 4.0

# Office POIs
[pois.office_government]
color = "#34495e"
radius = 4.0

[pois.office_company]
color = "#7f8c8d"
radius = 3.5

# Healthcare POIs
[pois.healthcare_doctor]
color = "#e74c3c"
radius = 3.5

[pois.healthcare_dentist]
color = "#e74c3c"
radius = 3.5

# Transport POIs
[pois.public_transport]
color = "#3498db"
radius = 3.0

# Place POIs (cities, towns, etc.)
[pois.place_city]
color = "#2c3e50"
radius = 6.0

[pois.place_town]
color = "#34495e"
radius = 5.0

[pois.place_village]
color = "#7f8c8d"
radius = 4.0

[pois.default]
color = "#95a5a6"
radius = 2.5

# Font sizes for different road types
[road_label_fonts]
motorway = 11
trunk = 11
primary = 10
secondary = 9
tertiary = 9
residential = 8
unclassified = 8
service = 7

# Font sizes for different place types
[place_label_fonts]
city = 14
town = 12
village = 10
hamlet = 9
suburb = 10
default = 9
