# Modern Clean Style Configuration
# This style matches the clean, modern appearance shown in the screenshot
# with light backgrounds, clean roads, and distinctive POI markers

[background]
color = "#F5F5F5"  # Light gray/beige background

[water]
color = "#AAD3DF"  # Soft blue for water
opacity = 1.0

[landuse]
forest = "#E8F5E8"           # Very light green for forests
residential = "#F8F8F8"      # Almost white for residential
commercial = "#F8F8F8"       # Same as residential
industrial = "#F0F0F0"       # Slightly darker gray
cemetery = "#F0F0F0"         # Light gray
retail = "#F8F8F8"

[leisure]
park = "#E8F5E8"             # Light green for parks
playground = "#E8F5E8"
sport = "#E8F5E8"
recreation_ground = "#E8F5E8"
garden = "#E8F5E8"

[natural]
wood = "#E8F5E8"             # Light green for natural areas
forest = "#E8F5E8"
grass = "#E8F5E8"
grassland = "#E8F5E8"
scrub = "#E8F5E8"

[aeroway]
default = "#E0E0E0"          # Light gray for airports

[buildings]
fill = "#FFFFFF"             # Pure white buildings
stroke = "#D0D0D0"           # Light gray stroke
stroke_width = 0.3

[railway]
rail_color = "#B0B0B0"       # Gray for railways
rail_width = 1.5
rail_dash_color = "#FFFFFF"
rail_dash_width = 1.0
rail_dash_pattern = "8,4"

[boundaries]
administrative_color = "#C0C0C0"
administrative_width = 1.0
administrative_dash = "5,3"
administrative_opacity = 0.6

[labels]
# Font styling for labels
font_family = "Arial"
road_label_stroke = "#ffffff"
road_label_stroke_width = 2
poi_label_stroke = "#ffffff"
poi_label_stroke_width = 2
place_label_stroke = "#ffffff"
place_label_stroke_width = 2

# Road styling - clean and minimal
[roads.motorway]
color = "#FF6B35"            # Orange for major highways
width = 3.5
border_color = "#E55A2B"
border_width = 0.5

[roads.motorway_link]
color = "#FF6B35"
width = 2.0
border_color = "#E55A2B"
border_width = 0.5

[roads.trunk]
color = "#FF8C42"            # Lighter orange for trunk roads
width = 3.0
border_color = "#E67A35"
border_width = 0.5

[roads.trunk_link]
color = "#FF8C42"
width = 1.8
border_color = "#E67A35"
border_width = 0.5

[roads.primary]
color = "#FFB84D"            # Yellow-orange for primary roads
width = 2.5
border_color = "#E6A642"
border_width = 0.5

[roads.primary_link]
color = "#FFB84D"
width = 1.5
border_color = "#E6A642"
border_width = 0.5

[roads.secondary]
color = "#FFFFFF"            # White for secondary roads
width = 2.0
border_color = "#D0D0D0"
border_width = 0.8

[roads.secondary_link]
color = "#FFFFFF"
width = 1.5
border_color = "#D0D0D0"
border_width = 0.8

[roads.tertiary]
color = "#FFFFFF"            # White for tertiary roads
width = 1.8
border_color = "#D0D0D0"
border_width = 0.8

[roads.tertiary_link]
color = "#FFFFFF"
width = 1.3
border_color = "#D0D0D0"
border_width = 0.8

[roads.residential]
color = "#FFFFFF"            # White for residential roads
width = 1.5
border_color = "#E0E0E0"
border_width = 0.6

[roads.service]
color = "#FFFFFF"            # White for service roads
width = 1.0
border_color = "#E0E0E0"
border_width = 0.4

[roads.unclassified]
color = "#FFFFFF"            # White for unclassified roads
width = 1.2
border_color = "#E0E0E0"
border_width = 0.5

[roads.living_street]
color = "#FFFFFF"
width = 1.2
border_color = "#E0E0E0"
border_width = 0.5

[roads.pedestrian]
color = "#F5F5F5"            # Light gray for pedestrian areas
width = 1.0
border_color = "#D0D0D0"
border_width = 0.3

[roads.footway]
color = "#E0E0E0"            # Gray for footways
width = 0.8
border_color = "#C0C0C0"
border_width = 0.2

[roads.path]
color = "#E0E0E0"            # Gray for paths
width = 0.6
border_color = "#C0C0C0"
border_width = 0.2

[roads.cycleway]
color = "#B3D9FF"            # Light blue for cycle ways
width = 0.8
border_color = "#8CC8FF"
border_width = 0.2

[roads.track]
color = "#D4B896"            # Brown for tracks
width = 0.8
border_color = "#C4A886"
border_width = 0.2

# Points of Interest styling to match screenshot
[pois.school]
color = "#4CAF50"
radius = 4.0

[pois.university]
color = "#4CAF50"
radius = 5.0

[pois.kindergarten]
color = "#4CAF50"
radius = 3.5

# Restaurants and food - orange/red markers
[pois.restaurant]
color = "#FF6B35"
radius = 4.0

[pois.cafe]
color = "#FF8C42"
radius = 3.5

[pois.fast_food]
color = "#FF6B35"
radius = 3.5

[pois.bar]
color = "#FF6B35"
radius = 3.5

[pois.pub]
color = "#FF6B35"
radius = 3.5

# Healthcare - red cross or red circle
[pois.hospital]
color = "#F44336"
radius = 5.0

[pois.clinic]
color = "#F44336"
radius = 4.0

[pois.pharmacy]
color = "#F44336"
radius = 3.5

# Shopping - blue circles
[pois.shop]
color = "#2196F3"
radius = 3.5

[pois.supermarket]
color = "#2196F3"
radius = 4.0

[pois.mall]
color = "#2196F3"
radius = 4.5

# Transportation - gray circles
[pois.bus_stop]
color = "#757575"
radius = 2.5

[pois.subway_entrance]
color = "#757575"
radius = 3.0

[pois.parking]
color = "#757575"
radius = 3.0

# Tourism - purple circles
[pois.hotel]
color = "#9C27B0"
radius = 4.0

[pois.museum]
color = "#9C27B0"
radius = 4.0

[pois.attraction]
color = "#9C27B0"
radius = 4.0

# Banks and finance - green squares
[pois.bank]
color = "#4CAF50"
radius = 3.5

[pois.atm]
color = "#4CAF50"
radius = 2.5

# Default for other POIs
[pois.default]
color = "#9E9E9E"
radius = 2.5

# Add required fields for the structure
[road_label_fonts]
motorway = 12
trunk = 11
primary = 10
secondary = 9
tertiary = 8
residential = 7
default = 6

[place_label_fonts]
city = 14
town = 12
village = 10
hamlet = 8
default = 9
